### ISSUE TITLE
내가 생각해도 이건 노드에서 쌉가능일듯

### ISSUE THREAD

**Issue by jeonghyeon-net** [surplus-developer/PyConKorea2019#1]
https://github.com/surplus-developer/PyConKorea2019/blob/master/Conference/run_multiple_in_one_django.md

위 기술을 노드에서 구현한다치면 어떻게 해야할까

**Comment by startergate** [comment]
뭐 도메인별로 나눠주는 미들웨어 하나 만들면 되지 않을까

**Comment by jeonghyeon-net** [comment]
흠, 내가 한번 시간내서 만들어볼까?

**Comment by startergate** [comment]
근데 미들웨어 하나 가지고 안되긴 할거임

**Comment by startergate** [comment]
라우터 모듈부터 고쳐야될걸
